### ISSUE TITLE
Filter displayed symbols

### ISSUE THREAD

**Issue by pistou** [atom/symbols-view#101]
Is there a way to **filter** symbols displayed in the tree view?

Here's an example (see image bellow):
I work on a PHP class with *a lot* of public vars (declared at the begining). The symbols tree view gives me only *var symbols* at the beginning, and I have to scroll down a ton to see actual *function symbols* (with var symbols in it..).

I'd like to configure the addon so it **displays only** *function symbols*, or **ignore** *var symbols*.

![symbols-tree-view](https://cloud.githubusercontent.com/assets/6703711/7807761/7846c404-038e-11e5-9c42-3785c702d20a.jpg)

**Comment by lee-dohm** [comment]
I think you're looking for the [symbols-tree-view package](https://atom.io/packages/symbols-tree-view)?

**Comment by pistou** [comment]
Yes indeed.

I messed up with the link in their description.
I'll submit an issue on their repo.
