### ISSUE TITLE
Navigate between symbols using keyboard

### ISSUE THREAD

**Issue by alefragnani** [atom/symbols-view#104]
Hi,

An interesting _(missing)_ feature in Symbols View is the ability to _automatically select the symbol/move to the line_, when you use the keyboard _(up and down arrows)_ to navigate between the list of symbols. And also when you _filter the symbols_, since the first symbol of the list is also updated. 

Thanks

**Comment by mnquintana** [comment]
Thanks for the suggestion! This is a duplicate of https://github.com/atom/symbols-view/issues/19 – please subscribe there for updates.
