### ISSUE TITLE
Add provider API

### ISSUE THREAD

**Issue by hedefalk** [atom/symbols-view#109]
I'm building a package for doing Scala development which uses Ensime which is basically a server/client IDE solution for Scala. I'm trying as far as possible to use the standard Atom components for "standard features". It would be really nice if I could hook up into symbols-view as a provider programmatically. We can and need to do better than ctags.

**Comment by radicaled** [comment]
Seconding this request for very similar reasons. It looks like the `atom-package` also has this need, as they override the `symbols:go-to[...]` command and build their own symbol navigator that looks almost exactly like `symbols-view`.

There's probably several more packages that need this. A provider API would definitely be an awesome addition.

**Comment by alexrussell** [comment]
:+1:, see #103

I guess the idea is that (like autocomplete these days) we can have per-language providers. But if a provider is not available for a given file, symbols-view could still default to using ctags?

**Comment by montegoulding** [comment]
:+1: Very helpful for any language not supported by ctags.

**Comment by 50Wliu** [comment]
See also #70 - can this be closed in favor of that issue?

**Comment by alexrussell** [comment]
@50Wliu From my perspective, yes this looks to be the same thing, and #70 is more mature (and specific).
