### ISSUE TITLE
Help: how to add symbols for language XXX

### ISSUE THREAD

**Issue by spencerlyon2** [atom/symbols-view#118]
I maintain a package for the Julia language

I would like to add support in this package for Julia symbols. To do this do I just add to the `.ctags` file here? If so, would something like [this](https://github.com/JuliaLang/julia/blob/master/contrib/ctags) work?

(link to issue in julia repo: JuliaLang/atom-language-julia#29)

**Comment by kevinsawicki** [comment]
Yeah, a pull request with additions to the file stored in this repository that you linked to would be great.

Eventually this should be made an service API for additions.
