### ISSUE TITLE
Show list of symbols on a pane

### ISSUE THREAD

**Issue by biji** [atom/symbols-view#165]
Please add list of symbols on a pane, which we can click without pressing Ctrl-R

**Comment by Altiano** [comment]
https://atom.io/packages/symbols-tree-view

**Comment by 50Wliu** [comment]
Thanks @Altiano for giving a link to a package!  I'm going to close this out since it looks like the asked-for functionality has been implemented in a package.

**Comment by biji** [comment]
I mean, this feature should be built in atom. i have used symbols tree view, but it is buggy.
We just want all symbol listed just like pressing Ctrl R, but with filter, for example list all functions and class only

Thanks

**Comment by evmorov** [comment]
Agree with @biji. symbols tree view is really buggy

**Comment by abstractpenguin** [comment]
https://atom.io/packages/symbols-list is a newer package that might meet your needs. Looks cleaner and less buggy than symbols-tree-view.

**Comment by aidistan** [comment]
Hopes https://atom.io/packages/symbols-view-plus would also fit your guys' need. It has already supported docks by now.

**Comment by onetrev** [comment]
Another new package that looks promising is https://atom.io/packages/structure-view
