### ISSUE TITLE
toggle-file-symbol doesn't read project's .tags files

### ISSUE THREAD

**Issue by chenglou** [atom/symbols-view#167]
Correct me if I'm wrong, but the whole code path starting from https://github.com/atom/symbols-view/blob/f36b81fe8358f5e3e300b6bbf43c33e995f93760/lib/main.coffee#L9 to https://github.com/atom/symbols-view/blob/f36b81fe8358f5e3e300b6bbf43c33e995f93760/lib/tag-generator.coffee#L56 doesn't take into consideration a project's custom `.tags` files. For any language not recognized by the ctags-config file or ctags itself, toggle-file-symbol returns nothing.

**Comment by lee-dohm** [comment]
That's correct. The file symbols list is generated on the fly.
