### ISSUE TITLE
No Symbols found

### ISSUE THREAD

**Issue by NerdPad** [atom/symbols-view#173]
I have multiple folders open in atom, then I open a JavaScript file, which contains functions & constants. When I hit CMD+r I get "No Symbols Found".

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* Can you include a JS file that reproduces this issue?

**Comment by dannyfritz** [comment]
I have the same thing on [this file](https://github.com/dannyfritz/handemade-quake-js/blob/0676bef/main/electronquake.js).

![atom_2016-04-28_07-53-24](https://cloud.githubusercontent.com/assets/315788/14888194/4f53c000-0d16-11e6-893b-122a3b9ac0e7.png)

**Comment by NerdPad** [comment]
Strange. I exited atom, and ran it in safe mode. And now symbols work even in normal mode.

Atom Version:
```
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

OS: OSX El Capitan

**Comment by dannyfritz** [comment]
That would imply a package is messing with it I would think.

**Comment by NerdPad** [comment]
Nevermind, it's still not working. I restarted atom and it's still broken. Works in safe mode.

@dannyfritz Yup. Any clue how to find out which package is messing with it?

**Comment by dannyfritz** [comment]
https://atom.io/packages/package-cop

**Comment by NerdPad** [comment]
@dannyfritz will report back.

**Comment by dannyfritz** [comment]
I will report mine doesn't work in safe mode. So we have different problems I think.

**Comment by lee-dohm** [comment]
@dannyfritz Please file a new Issue so that we can track these separately. It appears that the style of function declaration in use in that file you linked to isn't supported in the current JS regex. You may want to look at the recent PRs enhancing the JS support.

**Comment by frytyler** [comment]
We use Coldfusion as our main Server Side language and I noticed that the Symbol look up doesn't work at all in .CFC files. Is there support for Coldfusion or is this something I should get working and submit a Pull Request.

**Comment by lee-dohm** [comment]
@NerdPad Any updates on this?

**Comment by lee-dohm** [comment]
@NerdPad We haven't heard anything back from you, so we're going to assume that this is no longer a problem. Please reopen with some more information if that is not the case! :grinning:

**Comment by cronco** [comment]
@lee-dohm Sorry to comment in an already closed issue, but I seem to have the same problem.

OS: OS X 10.11.4
Atom: Both 1.7.3 and 1.8.0-beta3

Debugging steps tried: stable (1.7.3) works in safe mode, but it doesn't in normal mode with all community plugins disabled and a clean `init.coffee`
 Atom-beta 1.8.0-beta3 worked on first run, but after restart it doesn't work as well.

**Comment by dperetti** [comment]
Exact same issues as @cronco is describing. Can't figure out. Hasn't work for weeks for weeks. Then had been working for a couple days. Then stopped working again for no apparent reason. Works in safe mode.

**Comment by dperetti** [comment]
Oh my how about this, I can reproduce the issue now !

Actually, it's not that it works in safe mode by launching atom with `atom --safe`.
It **doesn't work when Atom was launched from the Finder** and it does work **when Atom was launched from the command line** (no need to `atom --safe`, it works with `atom`!)

**Comment by cronco** [comment]
Oh wow, @dperetti, that's right. and it might also be a good place to start the debugging.

**Comment by 50Wliu** [comment]
@dperetti @cronco can one of you open a new issue for that please?  Thanks!

**Comment by acorbin3** [comment]
For me on windows I was racking my brain on pressing Ctr-R but I was suppose to press Alt-R!

**Comment by lee-dohm** [comment]
@acorbin3 According to [the keymap](https://github.com/atom/symbols-view/blob/fbce559ebfaec4ddb72fee16708d4a21e6410820/keymaps/symbols-view.cson#L6-L7), the key binding on Windows is <kbd>Ctrl+R</kbd>, not <kbd>Alt+R</kbd>. If you've changed that by altering your keymap or by installing a package that does, you may want to review your list of key bindings in the Settings View.

**Comment by lodinv** [comment]
Программисты atom идиоты! Конченные.

**Comment by lee-dohm** [comment]
@lodinv your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by GLoThreeSixNine** [comment]
@acorbin3 Thank you greatly! your comment, followed by @lee-dohm's input, was exactly what lead me to water. "No Symbols Found" problem fixed.

**Comment by neilpip** [comment]
Apologies for commenting on a closed thread but the key binding is indeed Alt+R. What caused my initial issue today was not naming my file in .rb extension. After renaming it, Alt+R worked. I suppose the "missing symbol" was the extension.

**Comment by Michaelovesyoubitch** [comment]
> @acorbin3 According to [the keymap](https://github.com/atom/symbols-view/blob/fbce559ebfaec4ddb72fee16708d4a21e6410820/keymaps/symbols-view.cson#L6-L7), the key binding on Windows is Ctrl+R, not Alt+R. If you've changed that by altering your keymap or by installing a package that does, you may want to review your list of key bindings in the Settings View.

But it works only on Alt+R. Magic.

**Comment by Prajulaa** [comment]
> For me on windows I was racking my brain on pressing Ctr-R but I was suppose to press Alt-R!

Thank you!

**Comment by Mike-773** [comment]
I am running it on Linux Mint and had the same issue with "No Symbols Found". 
I used Alt R and it worked. Thanks for your help guys.
