### ISSUE TITLE
go-to-declaration does not center around symbol

### ISSUE THREAD

**Issue by anaskiee** [atom/symbols-view#181]
When triggerring function go-to-declaration, the editor window is not center around the symbol as expected.

I fixed it by doing this in lib/symbols-view.coffee : 
```
-      editor.scrollToBufferPosition(position, center: true)
       editor.setCursorBufferPosition(position)
       editor.moveToFirstCharacterOfLine() if beginningOfLine
+      editor.scrollToBufferPosition(position, center: true)
```

You can analyse it by breaking into text-editor-presenter.js functions : 
- TextEditorPresenter.prototype.requestAutoscroll
- TextEditorPresenter.prototype.commitPendingLogicalScrollTopPosition

It seems that the functions `setCursorBufferPosition` and `moveToFirstCharacterOfLine` override the option `{center: true}` of `scrollToBufferPosition`. As a consequence, the function `commitPendingLogicalScrollTopPosition` doesn't have the option anymore.
It is due to the fact that the calls are not synchronous, they're stored as event and are somehow concurrent...

I can open a pull request if needed

**Comment by 50Wliu** [comment]
> I can open a pull request if needed

Yes please!  Contributions always welcome.

**Comment by anaskiee** [comment]
Actually, I found that there is already a pull request associated to this bug
https://github.com/atom/symbols-view/pull/136

The issue associated is the following : https://github.com/atom/symbols-view/issues/132

**Comment by 50Wliu** [comment]
Ok, then I'm closing this issue in favor of #132.
