### ISSUE TITLE
Ctrl+r does not list all functions in cpp file

### ISSUE THREAD

**Issue by arrchana** [atom/symbols-view#185]
I have installed exuberant-ctags package, and have run `ctags -R .` in my project directory. It created a tags file which contains all the functions, variables, etc. However, atom still doesn't list all the functions available in my cpp file. How can I get this to work?

The same file when opened in Sublime Text, lists all the functions available in the file. I love using Atom, please help me get this to work. Thanks!

**Comment by 50Wliu** [comment]
[Qe're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
