### ISSUE TITLE
ctags-darwin performance

### ISSUE THREAD

**Issue by ilyakatz** [atom/symbols-view#191]
I've noticed that after a few saves `ctags-darwin` takes over my computer - multiple instances of it are running and hogging the CPU. 

![image](https://cloud.githubusercontent.com/assets/282514/17526509/62badd48-5e1c-11e6-9db8-8bf715a42aa0.png)

Is there a way to configure it so that only one instance of ctags-darwin is running? In the mean, I disabled `symbols-view` package and it still runs ctags. How can I stop it?

**Comment by lee-dohm** [comment]
What is the size of the file that you're editing when this happens? Is the actual file available publicly for us to reproduce the problem?

**Comment by ilyakatz** [comment]
Actually, turns out it was a different package that was spawning all these processes. I will follow up with them.

**Comment by derwaldgeist** [comment]
@ilyakatz I am facing the same problem. Could you please tell me what package you were using? Thx.

**Comment by ilyakatz** [comment]
sorry @derwaldgeist, i don't remember by now. I stopped using ctags at this point and use built in atom indexing and performance is sufficient for my codebase

**Comment by derwaldgeist** [comment]
@ilyakatz No problem, thanks anyways for your fast reply!

**Comment by lacostenycoder** [comment]
Can we reopen this issue?  I'm getting massive CPU spikes even when I disable this package.
In developer console I'm seeing tons of errors like this:

```
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/snapdragon/lib/source-maps.js
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/sockjs/lib/sockjs.js

(anonymous) @ symbol-gen-view.coffee? [sm]:73
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/sockjs/lib/trans-eventsource.js

(anonymous) @ symbol-gen-view.coffee? [sm]:73
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/sockjs/lib/trans-htmlfile.js

(anonymous) @ symbol-gen-view.coffee? [sm]:73
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/sockjs/lib/trans-jsonp.js

(anonymous) @ symbol-gen-view.coffee? [sm]:73
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/sockjs/lib/trans-websocket.js

(anonymous) @ symbol-gen-view.coffee? [sm]:73
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/sockjs/lib/trans-xhr.js

(anonymous) @ symbol-gen-view.coffee? [sm]:73
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/sockjs/lib/transport.js

(anonymous) @ symbol-gen-view.coffee? [sm]:73
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/sshpk/lib/utils.js

(anonymous) @ symbol-gen-view.coffee? [sm]:73
symbol-gen-view.coffee? [sm]:73 symbol-gen: ctag:stderr ctags-darwin: Warning: ignoring null tag in node_modules/svgo/plugins/_path.js
```
