### ISSUE TITLE
symbol access through global api

### ISSUE THREAD

**Issue by samu** [atom/symbols-view#23]
I was thinking about a feature that would let you step back and forth between symbols in a file (for example alt-down to locate the cursor to the next possible symbol). Currently, `FileView` is responsible for generating and caching all symbols for a file. I was wondering if it was possible to refactor this logic out of that class and make it available through a global api, so one could access symbols of a file independently.

**Comment by kevinsawicki** [comment]
Closing this out in favor of https://github.com/atom/symbols-view/issues/70 which talks about a service for providing symbols.
