### ISSUE TITLE
Updating to “symbols-view@0.118.1” failed

### ISSUE THREAD

**Issue by wearymax** [atom/symbols-view#232]
The symbols-view package is bundled with Atom and should not be explicitly installed.
You can run `apm uninstall symbols-view` to uninstall it and then the version bundled
with Atom will be used.

> ctags@3.0.0 install /private/var/folders/b8/6ypsd46j7ys0d6r90bmkp9v40000gn/T/apm-install-dir-117829-4377-1arrhwj.psdvg3nmi/node_modules/symbols-view/node_modules/ctags
> node-gyp rebuild

/private/var/folders/b8/6ypsd46j7ys0d6r90bmkp9v40000gn/T/apm-install-dir-117829-4377-1arrhwj.psdvg3nmi
`-- (empty)

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/b8/6ypsd46j7ys0d6r90bmkp9v40000gn/T/apm-install-dir-117829-4377-1arrhwj.psdvg3nmi/node_modules/symbols-view/node_modules/ctags
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/b8/6ypsd46j7ys0d6r90bmkp9v40000gn/T/apm-install-dir-117829-4377-1arrhwj.psdvg3nmi/package.json'
npm WARN apm-install-dir-117829-4377-1arrhwj.psdvg3nmi No description
npm WARN apm-install-dir-117829-4377-1arrhwj.psdvg3nmi No repository field.
npm WARN apm-install-dir-117829-4377-1arrhwj.psdvg3nmi No README data
npm WARN apm-install-dir-117829-4377-1arrhwj.psdvg3nmi No license field.
npm ERR! Darwin 17.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mpanov/.atom/.apm/.apmrc" "--userconfig" "/Users/mpanov/.atom/.apmrc" "install" "/private/var/folders/b8/6ypsd46j7ys0d6r90bmkp9v40000gn/T/d-117829-4377-qpyne.o421nvobt9/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ctags@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ctags
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/b8/6ypsd46j7ys0d6r90bmkp9v40000gn/T/apm-install-dir-117829-4377-1arrhwj.psdvg3nmi/npm-debug.log
npm ERR! code 1

**Comment by thomasjo** [comment]
Taken from your issue body:
> The symbols-view package is bundled with Atom and should not be explicitly installed.
> You can run apm uninstall symbols-view to uninstall it and then the version bundled
> with Atom will be used.

Uninstall the package by following the guidance in the error message.
