### ISSUE TITLE
Add service-hub Based API For Symbols Providers

### ISSUE THREAD

**Issue by joefitzgerald** [atom/symbols-view#70]
@maxbrunsfeld won't find it surprising that I would want to add this, but I have an outstanding pull request in `go-plus` to [add support for `godef`](https://github.com/joefitzgerald/go-plus/pull/137) to the package. [`godef`](https://code.google.com/p/rog-go/source/browse/#hg%2Fexp%2Fcmd%2Fgodef) provides the location of the definition of the item at a buffer position for `.go` files.

I have a ton of experience implementing an API like this for `autocomplete-plus`, but that wasn't a core package, so I'm mostly looking for a green flag to proceed in creating a pull request with this functionality so the responsibility for triggering `go to definition` isn't in `go-plus`, but rather in `symbols-view`, and so `symbols-view` can determine the correct provider for the current scope of the current cursor.

@maxbrunsfeld Could be an opportunity to test out the config-based approach for service-hub service definition also, depending on your timelines for that.

**Comment by maxbrunsfeld** [comment]
@joefitzgerald This is a great idea :flags:. We're going to ship atom/atom#5277 very soon and we'd love to have you test out the new service system. Please let us know if we can help with this at all. Thanks!

**Comment by park9140** [comment]
@maxbrunsfeld, I would also be interested in this, for the `atom-typescript-tools` plugin,  I've been providing my own view for `go to definition`.  In addition to go to definition typescript has interfaces so I could use this for my `find implementations` functionality. 

Also haven't implemented yet, but `typescript services` which I base the plugin around provides integrated symbol search which should really be used by the find symbols in project over the base implementation here.

**Comment by maxbrunsfeld** [comment]
@park9140 that sounds really awesome. I hope you find this new API useful for these applications. It'd be great to get your and @joefitzgerald's feedback early.

**Comment by skandasoft** [comment]
any idea when this will be released as I see all item are complete

**Comment by basarat** [comment]
@joefitzgerald Is there any progress on this. Is there some code I should be reviewing?

**Comment by joefitzgerald** [comment]
I've made no progress on this yet; not enough time.

**Comment by ferdynice** [comment]
Is this ticket still relevant?

Can we already used other symbols providers beside ctags?
