### ISSUE TITLE
No symbols generated for some file

### ISSUE THREAD

**Issue by xndcn** [atom/symbols-view#87]
For some file, such as this one: https://gist.github.com/xndcn/9c401a701c8d91bdf5a8/raw/71dfba5e794a07d3d851d40e56be24538dcda1a7/ltxml.js

No symbols will be generated, it just shows (on `Ubuntu`):
![screen](https://cloud.githubusercontent.com/assets/1317792/6797835/c0033e7c-d241-11e4-912f-3977fc2893d1.png)

**Comment by 50Wliu** [comment]
What version of Atom is this?  If it's not 0.187.0, could you please update?  Can you reproduce this in safe mode (`atom --safe`)?  Is there a pattern of some sort in the files that don't have symbols?
Sorry for the multiple questions, but answering them will probably help us better understand this issue.

**Comment by 50Wliu** [comment]
* I see you've already written a PR for this.  I guess you can ignore me then ;P
